### PR TITLE
Tile background color change

### PR DESCRIPTION
**Pull request by DavidGrygar**

### CODE REVIEW

**Review by Drekorian — APPROVED** [review]

**Comment by hrach** [comment]
I'm thinking whether the implementation couldn't be a different in a way that the theming would make it work (aka employ more composition):

```kotlin
        ProvideColors(OrbitTheme.colors.asInfoTheme()) {
            Tile(
                title = { Text("Title") },
                onClick = {},
                description = { Text("Description") },
            )
        }
```

Before introducing ButtonPrimitive, we did something similar with button. Maybe we would have to differentiate between subtle/main theme 🤔

**Comment by DavidGrygar** [comment]
> I wonder whether the implementation couldn't be a different in a way that the theming would make it work (aka employ more composition):
> 
> ```kotlin
>         ProvideColors(OrbitTheme.colors.asInfoTheme()) {
>             Tile(
>                 title = { Text("Title") },
>                 onClick = {},
>                 description = { Text("Description") },
>             )
>         }
> ```
> 
> Before introducing ButtonPrimitive, we did something similar with button. Maybe we would have to differentiate between subtle/main theme 🤔

I tried it and it didn't work at all. No color changes.

**Comment by hrach** [comment]
I know, the question is how we want to shape the API.

**Comment by DavidGrygar** [comment]
Closed, I will use one-time workaround.

**Pull request closed without merging**
